FROM golang:alpine
RUN apk add git

COPY . /go/src/transaction_server_1304/
RUN go get -u github.com/mediocregopher/radix.v2/redis
RUN go get -u github.com/mediocregopher/radix.v2/pool
RUN go get /go/src/transaction_server_1304
RUN go install /go/src/transaction_server_1304
RUN echo "Installed transaction 1304"

ENTRYPOINT /go/bin/transaction_server_1304
