version: "2"

services:
  redis:
    image: redis

  quote:
    build: quote_server/
    ports:
      - 1200:1200

  transaction:
    build: transaction_server/
    ports:
      - 1300:1300
    links:
      - redis
    depends_on:
      - redis
      - quote
    environment:
      REDIS_URL: redis:6379
      QUOTE_URL: quote:1200

  workload:
    image: golang:alpine
    volumes: 
      - .:/go/src/daytrading
    links:
      - redis
    depends_on:
      - transaction
      - redis
      - quote
    working_dir: /go/src/daytrading
    command: go build -o daytrading
    command: go run daytrading workload4
    environment:
      TRANSACTION_URL: transaction:1300


