version: "2"

services:
  redis:
    image: redis

  quote:
    build: quote_server/
    ports:
      - 1200:1200
  
  audit:
    build: audit_server/
    ports:
      - 1400:1400
    volumes:
      - .:/go/src/audit_server

  audit2:
    build: audit_server2/
    ports:
      - 1401:1401
    volumes:
      - .:/go/src/audit_server2

  transaction:
    build: transaction_server/
    ports:
      - 1300:1300
    links:
      - redis
    depends_on:
      - redis
      - quote
      - audit
      - audit2
    environment:
      REDIS_URL: redis:6379
      QUOTE_URL: quote:1200
      AUDIT_URL: audit:1400

  transaction2:
    build: transaction_server/
    ports:
      - 1301:1300
    links:
      - redis
    depends_on:
      - redis
      - quote
      - audit
      - audit2
    environment:
      REDIS_URL: redis:6379
      QUOTE_URL: quote:1200
      AUDIT_URL: audit:1400

  transaction3:
    build: transaction_server/
    ports:
      - 1302:1300
    links:
      - redis
    depends_on:
      - redis
      - quote
      - audit
      - audit2
    environment:
      REDIS_URL: redis:6379
      QUOTE_URL: quote:1200
      AUDIT_URL: audit:1400

  transaction4:
    build: transaction_server/
    ports:
      - 1303:1300
    links:
      - redis
    depends_on:
      - redis
      - quote
      - audit
      - audit2
    environment:
      REDIS_URL: redis:6379
      QUOTE_URL: quote:1200
      AUDIT_URL: audit:1400

  transaction5:
    build: transaction_server/
    ports:
      - 1304:1300
    links:
      - redis
    depends_on:
      - redis
      - quote
      - audit
      - audit2
    environment:
      REDIS_URL: redis:6379
      QUOTE_URL: quote:1200
      AUDIT_URL: audit:1400

  transaction6:
    build: transaction_server/
    ports:
      - 1305:1300
    links:
      - redis
    depends_on:
      - redis
      - quote
      - audit
      - audit2
    environment:
      REDIS_URL: redis:6379
      QUOTE_URL: quote:1200
      AUDIT_URL: audit:1400

  transaction7:
    build: transaction_server/
    ports:
      - 1306:1300
    links:
      - redis
    depends_on:
      - redis
      - quote
      - audit
      - audit2
    environment:
      REDIS_URL: redis:6379
      QUOTE_URL: quote:1200
      AUDIT_URL: audit:1400

  workload:
    image: golang:alpine
    volumes: 
      - .:/go/src/daytrading
    links:
      - redis
    depends_on:
      - transaction
      - transaction2
      - transaction3
      - transaction4
      - transaction5
      - redis
      - quote
      - audit
    working_dir: /go/src/daytrading
    command: go build -o daytrading
    command: go run daytrading workload4
    environment:
      TRANSACTION_URL: transaction:1300
      TRANSACTION2_URL: transaction2:1301
      TRANSACTION3_URL: transaction3:1302
      TRANSACTION4_URL: transaction4:1303
      TRANSACTION5_URL: transaction5:1304

  reverse-proxy:
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
