version: "2"

services:
  reverse-proxy:
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events

  redis:
    image: redis
    ports:
      - "6380:6379"

  redis2:
    image: redis
    ports:
      - "6381:6379"

  quote:
    build: quote_server/
    ports:
      - 1200:1200
  
  audit:
    build: audit_server/
    ports:
      - 1400:1400
    volumes:
      - .:/go/src/audit_server

  # workload:
  #   image: golang:alpine
  #   volumes: 
  #     - .:/go/src/daytrading
  #   links:
  #     - redis
  #     - redis2
  #   depends_on:
  #     - transaction
  #     - redis
  #     - redis2
  #     - quote
  #     - audit
  #   working_dir: /go/src/daytrading
  #   command: go build -o daytrading
  #   command: go run daytrading workload3
  #   environment:
  #     WEB_URL: web:1600
  #     TRANSACTION_URL: transaction:1300
  
  transaction:
    build: transaction_server/
    ports:
      - 1300-1310:80
    links:
      - redis
      - redis2
    depends_on:
      - redis
      - redis2
      - quote
      - audit
    environment:
      REDIS_URL: redis:6379
      REDIS2_URL: redis2:6379
      QUOTE_URL: quote:1200
      AUDIT_URL: audit:1400
    labels:
      - "traefik.backend=transaction"
      - "traefik.frontend.rule=Host:transaction"

  web:
    build: web_server/
    ports:
      - 1600:1600
    depends_on:
      - transaction
      - quote
    environment:
      REDIS_URL: redis:6379
      REDIS2_URL: redis2:6379
      QUOTE_URL: quote:1200
      AUDIT_URL: audit:1400
    volumes:
      - .:/go/src/servers/web_server

  web2:
    build: web_server2/
    ports:
      - 1601:1601
    depends_on:
      - transaction
      - quote
    environment:
      REDIS_URL: redis:6379
      REDIS2_URL: redis2:6379
      QUOTE_URL: quote:1200
      AUDIT_URL: audit:1400
    volumes:
      - .:/go/src/servers/web_server2
