version: "2"

services:
  redis:
    image: redis
    ports:
      - "6380:6379"

  redis2:
    image: redis
    ports:
      - "6381:6379"

  quote:
    build: quote_server/
    ports:
      - 1200:1200
  
  audit:
    build: audit_server/
    ports:
      - 1400:1400
    volumes:
      - .:/go/src/audit_server

  transaction:
    build: transaction_server/
    ports:
      - 1330:1300
    links:
      - redis
      - redis2
    depends_on:
      - redis
      - redis2
      - quote
      - audit
    environment:
      REDIS_URL: redis:6379
      REDIS2_URL: redis2:6379
      QUOTE_URL: quote:1200
      AUDIT_URL: audit:1400

  transaction2:
    build: transaction_server/
    ports:
      - 1301:1300
    links:
      - redis
      - redis2
    depends_on:
      - redis
      - redis2
      - quote
      - audit
    environment:
      REDIS_URL: redis:6379
      REDIS2_URL: redis2:6379
      QUOTE_URL: quote:1200
      AUDIT_URL: audit:1400

  transaction3:
    build: transaction_server/
    ports:
      - 1302:1300
    links:
      - redis
      - redis2
    depends_on:
      - redis
      - redis2
      - quote
      - audit
    environment:
      REDIS_URL: redis:6379
      REDIS2_URL: redis2:6379
      QUOTE_URL: quote:1200
      AUDIT_URL: audit:1400

  transaction4:
    build: transaction_server/
    ports:
      - 1303:1300
    links:
      - redis
      - redis2
    depends_on:
      - redis
      - redis2
      - quote
      - audit
    environment:
      REDIS_URL: redis:6379
      REDIS2_URL: redis2:6379
      QUOTE_URL: quote:1200
      AUDIT_URL: audit:1400

  transaction5:
    build: transaction_server/
    ports:
      - 1304:1300
    links:
      - redis
      - redis2
    depends_on:
      - redis
      - redis2
      - quote
      - audit
    environment:
      REDIS_URL: redis:6379
      REDIS2_URL: redis2:6379
      QUOTE_URL: quote:1200
      AUDIT_URL: audit:1400

  transaction6:
    build: transaction_server/
    ports:
      - 1305:1300
    links:
      - redis
      - redis2
    depends_on:
      - redis
      - redis2
      - quote
      - audit
    environment:
      REDIS_URL: redis:6379
      REDIS2_URL: redis2:6379
      QUOTE_URL: quote:1200
      AUDIT_URL: audit:1400

  transaction7:
    build: transaction_server/
    ports:
      - 1306:1300
    links:
      - redis
      - redis2
    depends_on:
      - redis
      - redis2
      - quote
      - audit
    environment:
      REDIS_URL: redis:6379
      REDIS2_URL: redis2:6379
      QUOTE_URL: quote:1200
      AUDIT_URL: audit:1400

  transaction8:
    build: transaction_server2/
    ports:
      - 1307:1301
    links:
      - redis
      - redis2
    depends_on:
      - redis
      - redis2
      - quote
      - audit
    environment:
      REDIS_URL: redis:6379
      REDIS2_URL: redis2:6379
      QUOTE_URL: quote:1200
      AUDIT_URL: audit:1400

  transaction9:
    build: transaction_server2/
    ports:
      - 1308:1301
    links:
      - redis
      - redis2
    depends_on:
      - redis
      - redis2
      - quote
      - audit
    environment:
      REDIS_URL: redis:6379
      REDIS2_URL: redis2:6379
      QUOTE_URL: quote:1200
      AUDIT_URL: audit:1400

  transaction10:
    build: transaction_server2/
    ports:
      - 1310:1301
    links:
      - redis
      - redis2
    depends_on:
      - redis
      - redis2
      - quote
      - audit
    environment:
      REDIS_URL: redis:6379
      REDIS2_URL: redis2:6379
      QUOTE_URL: quote:1200
      AUDIT_URL: audit:1400

  transaction11:
    build: transaction_server2/
    ports:
      - 1311:1301
    links:
      - redis
      - redis2
    depends_on:
      - redis
      - redis2
      - quote
      - audit
    environment:
      REDIS_URL: redis:6379
      REDIS2_URL: redis2:6379
      QUOTE_URL: quote:1200
      AUDIT_URL: audit:1400


  reverse-proxy:
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events

  machine:
    build: app/
    ports:
      - 2001:80
    depends_on:
      - quote
      - transaction
    labels:
      - "traefik.backend=machine-echo"
      - "traefik.frontend.rule=Host:machine-echo.example.com"
    environment:
      REDIS_URL: redis:6379
      REDIS2_URL: redis2:6379
      QUOTE_URL: quote:1200
      AUDIT_URL: audit:1400
      TRANSACTION_URL: transaction:1300
      
  web:
    build: web_server/
    ports:
      - 1600:1600
    depends_on:
      - quote
    labels:
      - "traefik.backend=web-echo"
      - "traefik.frontend.rule=Host:web-echo.example.com"
    environment:
      REDIS_URL: redis:6379
      REDIS2_URL: redis2:6379
      QUOTE_URL: quote:1200
      AUDIT_URL: audit:1400