version: "2"

services:
  transaction:
    environment:
      QUOTE_URL: quoteserve.seng.uvic.ca:4450
  transaction2:
    environment:
      QUOTE_URL: quoteserve.seng.uvic.ca:4450
  transaction3:
    environment:
      QUOTE_URL: quoteserve.seng.uvic.ca:4450
  transaction4:
    environment:
      QUOTE_URL: quoteserve.seng.uvic.ca:4450
  transaction5:
    environment:
      QUOTE_URL: quoteserve.seng.uvic.ca:4450
  transaction6:
    environment:
      QUOTE_URL: quoteserve.seng.uvic.ca:4450
  transaction7:
    environment:
      QUOTE_URL: quoteserve.seng.uvic.ca:4450
