version: "2"

services:
  redis:
    image: redis
    ports:
      - "6381:6379"

  redis2:
    image: redis
    ports:
      - "6382:6379"

  quote:
    build: quote_server/
    ports:
      - 1200:1200
  
  audit:
    build: audit_server/
    volumes:
      - .:/go/src/audit_server

  transaction:
    build: transaction_server/
    links:
      - redis
      - redis2
    depends_on:
      - redis
      - redis2
      - quote
      - audit
      - machine
    labels:
      - traefik.enable=true
      - "traefik.frontend.rule=Host:trans.docker.localhost"
    environment:
      REDIS_URL: redis:6379
      REDIS2_URL: redis2:6379
      QUOTE_URL: quote:1200
      AUDIT_URL: audit:1400

  traefik:
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  machine:
    build: app/
    ports:
      - 2001:80
    depends_on:
      - quote
    labels:
      - "traefik.backend=machine-echo"
      - "traefik.frontend.rule=Host:machine-echo.example.com"

  echo:
    image: katacoda/docker-http-server:v2
    labels:
      - "traefik.backend=echo"
      - "traefik.frontend.rule=Host:echo-echo.example.com"