FROM golang:alpine
RUN apk add git

COPY . /go/src/web_server2/
RUN go get -u github.com/gorilla/mux
RUN go get /go/src/web_server2
RUN echo "installed web2"
WORKDIR /go/src/web_server2

ENTRYPOINT /go/bin/web_server2
