FROM golang:alpine
RUN apk add git

COPY . /go/src/web_server/
RUN go get -u github.com/gorilla/mux
RUN go get /go/src/web_server
RUN echo "installed web"
WORKDIR /go/src/web_server

ENTRYPOINT /go/bin/web_server
