FROM golang:alpine
RUN apk add git

WORKDIR /go/src/transaction_server/
COPY . /go/src/transaction_server/
RUN go get -u github.com/mediocregopher/radix.v2/redis
RUN go get -u github.com/mediocregopher/radix.v2/pool
RUN go get /go/src/transaction_server
RUN go install /go/src/transaction_server
RUN echo "Installed transaction"

ENTRYPOINT /go/bin/transaction_server
